service: diablo-4-tg-bot

frameworkVersion: '>=3.19.0'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  stackName: ${self:service}
  environment:
    TOKEN: ${env:TOKEN}

functions:
  - ${file(./serverless/functions/webhook.yml)}

resources:
  - ${file(./serverless/resources/transform.yml)}
