Resources:
  NotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamodbNotificationsTableName}
      AttributeDefinitions:
        - AttributeName: chatId
          AttributeType: N
      KeySchema:
        - AttributeName: chatId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5