Transform:
  - AWS::Serverless-2016-10-31
Resources:
    SubscriptionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Subscriptions
        AttributeDefinitions:
          - AttributeName: chatId
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: boss
            AttributeType: BOOL
          - AttributeName: helltide
            AttributeType: BOOL
          - AttributeName: legion
            AttributeType: BOOL
        KeySchema:
          - AttributeName: chatId
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5